---
exclude_paths:
- hawk/vendor/*
- bootstrap-hawk/*
- hawk/app/assets/javascripts/gettext/*
engines:
  rubocop:
    enabled: true
  rubymotion:
    enabled: true
  bundler-audit:
    enabled: false
  eslint:
    enabled: true
  csslint:
    enabled: true
