language: ruby
branches:
  except:
    - rails-2_3
    - sle-11-sp2
rvm:
  - "1.9.2"
  - "1.9.3"
  - "2.0.0"
  - jruby-19mode
  - rbx
gemfile: hawk/Gemfile
script: sh -c 'cd hawk && if [ "$TRAVIS_RUBY_VERSION" = "rbx" ]; then bundle exec rake scanny ; fi && bundle exec rake'

