env:
  - RAILS_ENV: test

sudo: false
language: ruby
cache: bundler

branches:
  except:
    - rails-2_3
    - rails-3_2

rvm:
  - "2.5.0"

gemfile: hawk/Gemfile
script: sh -c 'cd hawk && ruby -- ./bin/bundle exec rspec'
