language: ruby
branches:
  except:
    - rails-2_3
    - sle-11-sp2
rvm:
  - "1.8.7"
  - "1.9.2"
  - "1.9.3"
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
gemfile: hawk/Gemfile
script: sh -c 'cd hawk && if [ "$TRAVIS_RUBY_VERSION" = "rbx-19mode" ]; then bundle exec rake scanny ; fi && bundle exec rake'

